version: "3.8"
name: "web-backend"

services:
  backend:
    image: web_backend_image
    container_name: web_backend
    tty: true
    build:
      dockerfile: build/Dockerfile
      context: .
    ports:
      - ${REST_SERVER_PORT}:${REST_SERVER_PORT}
    env_file:
      - .env
      - .local.env
    networks:
      - web-team-network

networks:
  web-team-network:
    external: true
    name: web_team_network
    
